# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Forms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Forms
  pod 'SNHttpRequest'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'
  pod 'EmptyStateKit'

end
